app = "hunains-travel-agent"

[build]
  command = "pip install -r requirements.txt"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
