flights = [
    # France (Paris)
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Paris",
        "country": "France",
        "date": "2025-08-01",
        "flight_number": "PK701",
        "airline": "PIA",
        "duration": "10h 30m",
        "price": 850,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Paris",
        "country": "France",
        "date": "2025-08-02",
        "flight_number": "AF255",
        "airline": "Air France",
        "duration": "11h 00m",
        "price": 890,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Paris",
        "country": "France",
        "date": "2025-08-03",
        "flight_number": "EK073",
        "airline": "Emirates",
        "duration": "10h 45m",
        "price": 910,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Paris",
        "country": "France",
        "date": "2025-08-04",
        "flight_number": "QR039",
        "airline": "Qatar Airways",
        "duration": "11h 15m",
        "price": 880,
    },
    # Philippines (Manila)
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Manila",
        "country": "Philippines",
        "date": "2025-08-01",
        "flight_number": "CX902",
        "airline": "Cathay Pacific",
        "duration": "12h 15m",
        "price": 920,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Manila",
        "country": "Philippines",
        "date": "2025-08-02",
        "flight_number": "PR321",
        "airline": "Philippine Airlines",
        "duration": "12h 30m",
        "price": 950,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Manila",
        "country": "Philippines",
        "date": "2025-08-03",
        "flight_number": "SQ912",
        "airline": "Singapore Airlines",
        "duration": "13h 05m",
        "price": 930,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Manila",
        "country": "Philippines",
        "date": "2025-08-04",
        "flight_number": "EK338",
        "airline": "Emirates",
        "duration": "12h 50m",
        "price": 940,
    },
    # Vietnam (Hanoi)
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Hanoi",
        "country": "Vietnam",
        "date": "2025-08-01",
        "flight_number": "VN395",
        "airline": "Vietnam Airlines",
        "duration": "11h 50m",
        "price": 880,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Hanoi",
        "country": "Vietnam",
        "date": "2025-08-02",
        "flight_number": "QR970",
        "airline": "Qatar Airways",
        "duration": "12h 10m",
        "price": 900,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Hanoi",
        "country": "Vietnam",
        "date": "2025-08-03",
        "flight_number": "TG550",
        "airline": "Thai Airways",
        "duration": "12h 00m",
        "price": 870,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Hanoi",
        "country": "Vietnam",
        "date": "2025-08-04",
        "flight_number": "EK392",
        "airline": "Emirates",
        "duration": "11h 30m",
        "price": 890,
    },
    # Japan (Tokyo)
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Tokyo",
        "country": "Japan",
        "date": "2025-08-01",
        "flight_number": "JL722",
        "airline": "Japan Airlines",
        "duration": "9h 45m",
        "price": 1100,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Tokyo",
        "country": "Japan",
        "date": "2025-08-02",
        "flight_number": "NH828",
        "airline": "All Nippon Airways",
        "duration": "10h 15m",
        "price": 1150,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Tokyo",
        "country": "Japan",
        "date": "2025-08-03",
        "flight_number": "EK318",
        "airline": "Emirates",
        "duration": "9h 55m",
        "price": 1120,
    },
    {
        "current_country": "Pakistan",
        "current_city": "Karachi",
        "destination": "Tokyo",
        "country": "Japan",
        "date": "2025-08-04",
        "flight_number": "QR806",
        "airline": "Qatar Airways",
        "duration": "10h 00m",
        "price": 1090,
    },
]


hotels = {
    "France": [
        {
            "name": "Hotel Eiffel",
            "city": "Paris",
            "rating": 4.5,
            "price_per_night": 150,
        },
        {
            "name": "Louvre Stay",
            "city": "Paris",
            "rating": 4.2,
            "price_per_night": 130,
        },
        {
            "name": "Franceian Comfort Inn",
            "city": "Paris",
            "rating": 4.1,
            "price_per_night": 120,
        },
        {
            "name": "Montmartre Boutique Hotel",
            "city": "Paris",
            "rating": 4.6,
            "price_per_night": 160,
        },
        {
            "name": "Champs Elysees Retreat",
            "city": "Paris",
            "rating": 4.4,
            "price_per_night": 145,
        },
        {
            "name": "Seine Riverside Hotel",
            "city": "Paris",
            "rating": 4.3,
            "price_per_night": 135,
        },
    ],
    "Philippines": [
        {
            "name": "Manila Seaside Inn",
            "city": "Manila",
            "rating": 4.0,
            "price_per_night": 100,
        },
        {
            "name": "Cebu Beach Resort",
            "city": "Cebu",
            "rating": 4.6,
            "price_per_night": 120,
        },
        {
            "name": "Boracay Paradise Hotel",
            "city": "Boracay",
            "rating": 4.4,
            "price_per_night": 115,
        },
        {
            "name": "Palawan Island Inn",
            "city": "Palawan",
            "rating": 4.3,
            "price_per_night": 105,
        },
        {
            "name": "Davao Tropic Stay",
            "city": "Davao",
            "rating": 4.2,
            "price_per_night": 98,
        },
        {
            "name": "Baguio Hilltop Hotel",
            "city": "Baguio",
            "rating": 4.1,
            "price_per_night": 102,
        },
    ],
    "Vietnam": [
        {
            "name": "Saigon Central Hotel",
            "city": "Ho Chi Minh City",
            "rating": 4.3,
            "price_per_night": 110,
        },
        {
            "name": "Hanoi Heritage Inn",
            "city": "Hanoi",
            "rating": 4.7,
            "price_per_night": 125,
        },
        {
            "name": "Da Nang Beachside Hotel",
            "city": "Da Nang",
            "rating": 4.5,
            "price_per_night": 120,
        },
        {
            "name": "Hue Imperial Stay",
            "city": "Hue",
            "rating": 4.2,
            "price_per_night": 108,
        },
        {
            "name": "Hoi An Lantern Resort",
            "city": "Hoi An",
            "rating": 4.6,
            "price_per_night": 130,
        },
        {
            "name": "Nha Trang City Inn",
            "city": "Nha Trang",
            "rating": 4.0,
            "price_per_night": 100,
        },
    ],
    "Japan": [
        {
            "name": "Tokyo Capsule Stay",
            "city": "Osaka",
            "rating": 4.8,
            "price_per_night": 140,
        },
        {
            "name": "Osaka Zen Hotel",
            "city": "Osaka",
            "rating": 4.5,
            "price_per_night": 135,
        },
        {
            "name": "Kyoto Garden Inn",
            "city": "Kyoto",
            "rating": 4.6,
            "price_per_night": 150,
        },
        {
            "name": "Sapporo Snow Lodge",
            "city": "Sapporo",
            "rating": 4.3,
            "price_per_night": 120,
        },
        {
            "name": "Nara Traditional Inn",
            "city": "Nara",
            "rating": 4.4,
            "price_per_night": 125,
        },
        {
            "name": "Hiroshima Peace Hotel",
            "city": "Hiroshima",
            "rating": 4.2,
            "price_per_night": 115,
        },
    ],
}
